### ISSUE TITLE
Loading Font Files from CSS

### ISSUE THREAD

**Issue by lauraGgit** [18F/fedramp-dashboard#10]
https://github.com/truetandem/fedramp-dashboard/blob/master/index.html#L15
Please make sure that once you move over to the uswds.css that you are loading your fonts as they do from the core_fonts `@font-face { /* … */ }` declarations as shown below:

https://github.com/18F/web-design-standards/blob/fd9018f2338c9ab1399769149c4205cbac30c519/src/stylesheets/core/_fonts.scss

**Comment by bmallred** [comment]
The references have been removed and will keep an eye on new usages to follow suit w/ the USWDS usages!
