### ISSUE TITLE
Blanket.js coverage

### ISSUE THREAD

**Issue by lauraGgit** [18F/fedramp-dashboard#11]
I am seeing in the jasmine test runner that Blanket.js is putting the coverage of fedramp.js at 72% while Coveralls is stating closer to 90%. It looks like blanket is a bit more strict on whether the code hits object properties, but I was curious about the difference to your knowledge in the coverage calculations.
 http://truetandem.github.io/fedramp-dashboard/test/

**Comment by bmallred** [comment]
Thanks for bringing this up. Looks like we haven't updated the test/index.html to include the additional tests. We'll add those and we should see numbers being more inline!

**Comment by bmallred** [comment]
We have it at 95.87% now with BlanketJS as of e0228ec. There are differences in the counting but I will have to look a bit deeper to find the differences.
