### ISSUE TITLE
Moving component template html files into own directory 

### ISSUE THREAD

**Issue by lauraGgit** [18F/fedramp-dashboard#12]
This is just a suggestion, but it seems like for clarity, it might sense to move the component templates in the `[src/fedramp.components](https://github.com/truetandem/fedramp-dashboard/tree/master/src/fedramp.components)` into their own subdirectory for easier navigation of this  directory.

**Comment by bmallred** [comment]
Not a problem (we're both using omnisearch/fuzzy-finders anyways)... what would make more sense?
- src/
  - fedramp.components
    - templates
  - fedramp.models
  - fedramp.services
  - fedramp
    - templates
    - home
      - templates
    - search
      - templates
    - sitemap
      - templates

or, maybe separate them from the code a bit more....
- src/
  - templates
    - components
    - home
    - search
    - sitemap
  - fedramp.components
  - fedramp.models
  - fedramp.services
  - fedramp
    - home
    - search
    - sitemap

or maybe some other scheme?

**Comment by floresj** [comment]
An alternative structure which aims to break up components (and their related child components) into their own dirs.
- src/
  - fedramp.components
    - tile
      - tile.component.js
      - tile-provider.html
      - tile-product.html
      - tile-assessor.html
    - grid/
      - grid.component.js
      - grid.component.html
      - grid-filter/
        - grid-filter.component.html
        - grid-filter.html
  - /more stuffs
