### ISSUE TITLE
When filtering by agency, CSPs with 0 authorizations are also displayed

### ISSUE THREAD

**Issue by openbrian** [18F/fedramp-dashboard#126]
**What did you do?**

Filter on Agency = Department of Energy

**What did you expect to see?**

I did not expect to see Adobe Sign.

**What did you see instead?**

Adobe Sign

**Additional Information**

According to data.json, Adobe Sign has no Leveraged_ATO_Letters.

 - What browser and version are you using?  Firefox :)
 - What operating system?  Debian Linux

**Comment by rhoesing** [comment]
Brian,

That is correct.  The reason you are seeing Adobe Sign is that Department of Energy are or are planning on using the product and working towards an authorization within 12 months.
