### ISSUE TITLE
Sprint 2 acceptance

### ISSUE THREAD

**Issue by jposi** [18F/fedramp-dashboard#13]
18F accepts the work done by True Tandem, with a note of the following issues that require resolution/conversation next week:
#12
#11
#10

**Comment by jposi** [comment]
cc: @pjsumm for your review/closeout.

**Comment by pjsumm** [comment]
TrueTandem accepts the approval of our Sprint 2 work and we will work with you on issues 10,11,12 to bring them to closure quickly.  Thank you!
