### ISSUE TITLE
A test fails when running locally

### ISSUE THREAD

**Issue by anthonygarvan** [18F/fedramp-dashboard#14]
Hey Team-

Minor issue when I was getting things set up, on following the directions (`npm install` && `npm test`), I get a error on one of the tests:

``` bash
PhantomJS 2.1.1 (Mac OS X 0.0.0) The helper service can convert date to mm/dd/YYYY FAILED
    Expected '08/22/2013' to be '08/23/2013'.
    /Users/anthonygarvan/Documents/Projects/fedramp-dashboard/test/fedramp.services/helper.service.test.js:18:64
```

I'm on node 4.1.0 and npm 2.14.4.

**Comment by bmallred** [comment]
Thanks we will take a look at it. Might be something with missing timezone information.
We're running node 6.3.0 and npm 3.10.5.

**Comment by bmallred** [comment]
@anthonygarvan changed the function calls to use the equivalent "UTC" functions. Let me know if this still fails on your end!

**Comment by bmallred** [comment]
Going to close this but if there is still an issue please don't hesitate to scold us!
