### ISSUE TITLE
CSS Issue on Landing Page

### ISSUE THREAD

**Issue by anthonygarvan** [18F/fedramp-dashboard#15]
Looks like there is an issue with the CSS on the landing page. Search box should not be above the rest of the header, but to the right of it. I'm on Chrome 51.

<img width="1068" alt="screen shot 2016-07-18 at 3 33 07 pm" src="https://cloud.githubusercontent.com/assets/2559082/16929385/3b247530-4cfd-11e6-8129-799ae21b9430.png">

**Comment by bmallred** [comment]
We copied it from [https://www.fedramp.gov/marketplace/compliant-systems/#](https://www.fedramp.gov/marketplace/compliant-systems/#) which had it underneath when I view it.

![searchbox](https://cloud.githubusercontent.com/assets/697855/16930298/8fea7dec-4d09-11e6-8701-ae97f2dcdf6e.png)

Chrome: Version 51.0.2704.106 (64-bit)

**Comment by floresj** [comment]
Moved search button next to search field.
