### ISSUE TITLE
Multiple `Export to CSV` buttons

### ISSUE THREAD

**Issue by lauraGgit** [18F/fedramp-dashboard#17]
This is very low priority but when we have a filtered list, this seems a bit redundant.

![image](https://cloud.githubusercontent.com/assets/5840989/17330739/f8b09446-5895-11e6-8ae1-74525f37844a.png)

**Comment by bmallred** [comment]
Removed the one under the grid and added stickiness to the one on the filter menu. 20e67379beaebaf9e66577f2c6e2c19390a4bc7a
