### ISSUE TITLE
In Print Dashboard when Status is chosen from top visual headers, print says status is undefinded

### ISSUE THREAD

**Issue by lauraGgit** [18F/fedramp-dashboard#19]
Given I have selected a status from the top filters,
When I select the print,
Then I would like to see that the status in the print view reflects the filter I chose. 

![image](https://cloud.githubusercontent.com/assets/5840989/17369900/1cf449ce-5968-11e6-93a1-1f5ba012ca05.png)

**Comment by floresj** [comment]
Fixed issue where label was not being populated when restoring grid filter state from a refresh.
