### ISSUE TITLE
Documentation - PWS Compliance

### ISSUE THREAD

**Issue by lauraGgit** [18F/fedramp-dashboard#27]
## README.md
- [x] Include a bit more documentation about how to perform maintenance on the local storage services.
- [x] Include the link back to the tests `http://truetandem.github.io/fedramp-dashboard/test/` given that is has an easier to read reporter than just the one in `npm test` https://github.com/truetandem/fedramp-dashboard/blob/gh-pages/README.md#executing-tests-and-coverage-reports 
- [x] Add documentation for the `npm run docgen` function
## Contributing.md
- [x] In lieu of the “Reporting Issues,” create an Issue Template. https://github.com/blog/2111-issue-and-pull-request-templates
- [x] `###Tooling Section` looks like it should be moved into the readme.

**Comment by lauraGgit** [comment]
Could you please make a note in Contributing.md that the issue template exists for the questions listed?

**Comment by bmallred** [comment]
Sure thing

**Comment by lauraGgit** [comment]
This looks good, you may just want to update the structure of the tree listed in the [Package Application] to reflect the changes from #29 / #30 (https://github.com/truetandem/fedramp-dashboard#packaging-application).

**Comment by bmallred** [comment]
Should be updated with e7b8fea

**Comment by lauraGgit** [comment]
🚀
