### ISSUE TITLE
Increasing Test Coverage - Recommended

### ISSUE THREAD

**Issue by lauraGgit** [18F/fedramp-dashboard#28]
While we did not explicitly state in the QASP, we would prefer that you expand your test coverage so that the `lcov` report generated at `http://localhost:8080/coverage/` so that the test suite will cover 90% of statements of code.  The current metric that Coveralls uses is `lines`.

As of earlier today (commit `a775309`), tests hit 1596/1812 statements (88.08%).  We recognize that you have achieved the 90% in terms of lines (471/476).

Moving to 90% statement coverage will help us ensure that future enhancements will be less likely to break our test suite.

**Comment by bmallred** [comment]
Just got the statement coverage to 90.23% as of https://github.com/truetandem/fedramp-dashboard/commit/5c24d57c15a13314c5ddeffee9e4e8e45520cbaf. Going to leave this open for the time being as a reminder for when we are making more changes today.

**Comment by lauraGgit** [comment]
Yup, this looks like its up to `90.6%` for statements.
