### ISSUE TITLE
Update Gulp Task - Recommended 

### ISSUE THREAD

**Issue by lauraGgit** [18F/fedramp-dashboard#29]
To improve load performance of the production site we recommend that you alter a number of the tasks performed in the `npm run package` gulp script.
- [x] Minify CSS for the `build/dest`
- [x] Bundle the js libs into the minified fedramp.min.js in `build/dest`. This would make it so you wouldn't need the separate `lib`, `build/lib`, or `build/dest/lib` directories and would then only require the site to load 1 js file.
- [x] Change the copy `fonts`, `img` task to just copy these directories from the `node_modules/uswds/dist` directories.  Then remove the directories from the committed repository.
- [x] When the `npm run package` is run do not copy unminified `fedramp.js` to `build/dest`

**Comment by bmallred** [comment]
So we went ahead and made another command `npm run build` to keep the unminified sources. This is necessary so the in-browser test and coverage suites can still operate.

**Comment by lauraGgit** [comment]
Liking the 
- minified css
- fully bundled JS
- directly copying the fonts/ uswds assets
- updated gulp tasks

**Comment by lauraGgit** [comment]
Also, the newly built `dist` folder seems to deploy correctly to the AWS bucket.
