### ISSUE TITLE
 Streamline Repository Directory Organization - Recommended

### ISSUE THREAD

**Issue by lauraGgit** [18F/fedramp-dashboard#30]
Some of the directory organization could be streamlined to make the `src => build/dest` pipeline more fluid. Many of these tasks would be contingent on reworking the Gulp tasks outlined in #29.
- [x] Add `dist` to git ignore.\* It looks like `lib`, `dist`, `css` are artifacts of the test suite and the gulp build process, and should be added to the .gitignore, as they do not need to be committed.
- [x] Move `sass` in to `src`\* to make it clear that that is compiled in the build process. 
- [x] Move the index.html into `src` as well. This would likely require an update to the Gulp script.

**Comment by floresj** [comment]
The index.html file was almost the death of this app.

**Comment by lauraGgit** [comment]
Much cleaner!
