### ISSUE TITLE
Use Git Subtree to build gh-pages branch - Nice to Have

### ISSUE THREAD

**Issue by lauraGgit** [18F/fedramp-dashboard#31]
Consider just pushing just the `build/dest` directory built via the `npm run package` to the gh-pages by using git subtree.

This would to allow us to have a development environment on `gh-pages` that more closely reflects the `build/dest` that the production environment runs on.

For documentation on this please see:
https://makingsoftware.wordpress.com/2013/02/16/using-git-subtrees-for-repository-separation/

https://gist.github.com/cobyism/4730490

**Comment by bmallred** [comment]
Implemented in [hooks/post-commit](../blob/master/hooks/post-commit).

**Comment by lauraGgit** [comment]
Noice! LTGM.
