### ISSUE TITLE
Separate Router Test Assertions into separate tests - Nice to Have

### ISSUE THREAD

**Issue by lauraGgit** [18F/fedramp-dashboard#32]
In the test [fedramp.routes.test.js](https://github.com/truetandem/fedramp-dashboard/blob/master/test/fedramp/fedramp.routes.test.js), it would be helpful if it were re-written several tests with individual assertions  for each route to be able to better ascertain where any router issues occur if they arise.

**Comment by bmallred** [comment]
Also added missing test for the dictionary route.

**Comment by lauraGgit** [comment]
LGTM! 👍 And interesting assertions you are using there. 😉
