### ISSUE TITLE
Match styling to fedramp.gov

### ISSUE THREAD

**Issue by jposi** [18F/fedramp-dashboard#33]
**Description**

Match styling of header of marketplace.fedramp.gov to headers of fedramp.marketplace.gov to keep consistency between pages.

**Ask**

Add:
- [x] Add Social Media Icons
- [x] Add "contact us" link
- [x] Shift navigation bar to be inline with FedRAMP logo as it is on fedramp.gov
- [x] Have "Marketplace" link be active on navigation bar (throughout dashboard)

**Additional info**
Here's an image of the fedramp.gov site:
<img width="1097" alt="screen shot 2016-08-09 at 5 00 04 pm" src="https://cloud.githubusercontent.com/assets/3505071/17533605/8683c690-5e53-11e6-8689-3e64cadb3894.png">

**Comment by jposi** [comment]
Oops - and here's the top of marketplace.fedramp.gov:
<img width="986" alt="screen shot 2016-08-09 at 5 06 51 pm" src="https://cloud.githubusercontent.com/assets/3505071/17533632/b0839204-5e53-11e6-88db-32d6fb100533.png">

**Comment by bmallred** [comment]
**Questions**
- [x] Do we need the _gutters_ applied to the entire page?
  **_Leave it as is**_
- [x] If we don't apply _gutters_ on the entire page should we keep the navigation menu gray bar to go the entire page width?
  **_Leave it as is**_
- [x] Are there any links in the navigation menu which need their target URL to be updated?
  **_Yes, see the comment below (they should be relative for the most part)**_
- [x] On the www.fedramp.gov site the Twitter and RSS icons scroll up and out of view on hover and should we do the same or is there another preferred behavior?
  **_Ground them**_
- [x] The search component now adheres to [U.S. Web Design Standards](https://standards.usa.gov/search-bar/) but does not at www.fedramp.gov. Which should we follow?
  **_Leave it as is**_

~~Some talking points during the daily meeting!~~

**Comment by jposi** [comment]
Links: 
MARKETPLACE
https://marketplace.fedramp.gov/#/products?status=FedRAMP%20Ready&sort=productName
MARKETPLACE > FedRAMP Compliant Systems. This should be renamed to: "FedRAMP Authorized Systems"
 https://marketplace.fedramp.gov/#/products?status=Compliant&sort=productName
MARKETPLACE > FedRAMP In-Process Systems
https://marketplace.fedramp.gov/#/products?status=In%20Process&sort=productName
MARKETPLACE > FedRAMP Ready Systems
https://marketplace.fedramp.gov/#/products?status=FedRAMP%20Ready&sort=productName
MARKETPLACE > Accredited 3PAOs
https://marketplace.fedramp.gov/#/assessors?sort=assessorName

**Comment by bmallred** [comment]
@jposi also added one for agencies according to @pjsumm's notes:

MARKETPLACE > Agencies
https://marketplace.fedramp.gov/#/agencies

**Comment by bmallred** [comment]
Related commits (forgot to include in the commit messages):
- e78c392c0af367f7ad480dfbe21e9b6c7386a1ec
- 0612c12cd5a4024a2b1ba6f5e429953c88480e7e
- 3e29856c9291cc1cf886817179bfdccf8faa876a
- f23c333385252cd3647d153419d59c92378f79cd
- 2d891c7c27a1684ad43079d20b0683d81f87f3c5
- 9df73dc10b1b16a60b02f69711f11d891a3669ec
- 78ed3edf574ed111a53bd262f09b305d799bf125

These have been merged in to the [master](https://github.com/truetandem/fedramp-dashboard/tree/master) branch as well as retained for historical purposes on the [header_adjustments](https://github.com/truetandem/fedramp-dashboard/tree/header_adjustments) branch.

**Comment by jposi** [comment]
Thanks.
