### ISSUE TITLE
Acceptance of Sprint 0

### ISSUE THREAD

**Issue by jposi** [18F/fedramp-dashboard#4]
Per the user stories completed as documented in this [google doc](https://docs.google.com/document/d/1Jb-mLb4T8ovXKriwqUg4t3htZSAqCE0XKvjn98kIePk/edit#) and on [Taiga](https://tree.taiga.io/project/truetandem-fedramp-dashboard/taskboard/sprint-0-planning-sprint-1), 18F and FedRAMP accept the work of TrueTandem in Sprint 0.

Great work - excited to see what happens in Sprint 1!

**Comment by jposi** [comment]
Feel free to close this as a mark of your acceptance/approval as well.

**Comment by pjsumm** [comment]
TrueTandem accepts the approval of our Sprint 0 work.  Thank you!
