### ISSUE TITLE
set up compliance masonry

### ISSUE THREAD

**Issue by stvnrlly** [18F/fedramp-dashboard#46]
https://github.com/18F/cg-compliance#starting-ato-documentation-for-cloudgov-applications

**Comment by lauraGgit** [comment]
@stvnrlly is this still necessary?

**Comment by stvnrlly** [comment]
Necessary? Not sure. But I'd still like to set it up, if you don't mind, since I haven't done it before.

**Comment by afeld** [comment]
Closing as stale.
