### ISSUE TITLE
Break Taiga webhooks

### ISSUE THREAD

**Issue by bmallred** [18F/fedramp-dashboard#49]
**What did you do?**

Received email notices about new issues posted to 18F owned repository via Taiga web hooks.

_Including steps for recreating it, if applicable._

Post issue at 18F/fedramp-dashboard
Drink coffee
Check issues on https://tree.taiga.io/project/truetandem-fedramp-dashboard/issues?page=1

**What did you expect to see?**

_Describe the desired behavior and what would deem this issue, bug, or feature
complete._

Issues do not get posted on Taiga

**Comment by lauraGgit** [comment]
@bmallred are you still seeing this?

**Comment by bmallred** [comment]
@lauraGgit nope, LGTM
