### ISSUE TITLE
Deployment to S3

### ISSUE THREAD

**Issue by bmallred** [18F/fedramp-dashboard#5]
It was discussed to possibly leverage S3 to host the static files. This would be beneficial since the Sites hosting is done through WordPress and it would allow various environments (staging, production, etc.) to be configured.

**Comment by bmallred** [comment]
@vzvenyach looks like it there was a deployment error at [line 834](https://travis-ci.org/truetandem/fedramp-dashboard/jobs/141057813#L834) in the TravisCI logs.

```
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.17/lib/dpl/provider/s3.rb:47:in `chdir': No such file or directory - build (Errno::ENOENT)
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.17/lib/dpl/provider/s3.rb:47:in `push_app'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.17/lib/dpl/provider.rb:143:in `block in deploy'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.17/lib/dpl/cli.rb:41:in `fold'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.17/lib/dpl/provider.rb:143:in `deploy'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.17/lib/dpl/provider/s3.rb:72:in `deploy'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.17/lib/dpl/cli.rb:32:in `run'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.17/lib/dpl/cli.rb:7:in `run'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.17/bin/dpl:5:in `<top (required)>'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by vdavez** [comment]
D'oh! Can you revert the merge, and I'll get it to work today. I probably should have labeled this as a `WIP: DON'T MERGE` until I got it working locally.

**Comment by bmallred** [comment]
Ha no worries. I just commented out the deployment section temporarily.

**Comment by vdavez** [comment]
So, I got this to work at 18F/fedramp-dashboard. It turns out that it was a whole thing involving the way that travis was encrypting the AWS keys. I'm going to close this issue here, because it's now working (check out https://s3.amazonaws.com/fedramp-dashboard-demo/index.html#/) and when we merge from the upstream repo, it will automatically deploy to S3. Woot!
