### ISSUE TITLE
Remove alpha link from header banner

### ISSUE THREAD

**Issue by jposi** [18F/fedramp-dashboard#55]
_Describe the desired behavior and what would deem this issue, bug, or feature
complete._
Link in banner is dead. Remove the URL

**What did you see instead?**
a 404 when you click the link.

**Comment by lauraGgit** [comment]
Remove just the `<a>` tag, not the text.

**Comment by lauraGgit** [comment]
This page has been put back up on the 18F site, so we can close this issue.
