### ISSUE TITLE
Move to a new CI/CD system

### ISSUE THREAD

**Issue by hollyallen** [18F/fedramp-dashboard#77]
This repository has been using Travis CI, however access to Travis CI is now turning off. When you need to use this repository again, convert it to a CI/CD system which is in the ITSP such as Circle CI.

**Comment by afeld** [comment]
Looks like this may be done?

**Comment by afeld** [comment]
Correction: it does not, and changes to the site aren't being deployed.

**Comment by afeld** [comment]
This site is now deployed via Federalist.
