### ISSUE TITLE
Total Authorization Count by Package ID not name

### ISSUE THREAD

**Issue by lauraGgit** [18F/fedramp-dashboard#9]
In reviewing the 
https://github.com/truetandem/fedramp-dashboard/blob/master/src/fedramp/home/home.controller.js#L322

I think that line 322 would probably be `if (p.pkgId && !counted.includes(p.pkgId)) {` as companies such as Microsoft, have multiple products although the same provider name.

I also believe that provider.length probably is sufficient to get this as the `groupby` function in the .gs script is by package id, but you might want to retain this to confirm.

Below is the full function for reference.

```
        self.totalAuthorized = function () {
            var totalAuthorized = 0;

            var counted = [];
            for (var i = 0; i < providers.length; i++) {
                var p = providers[i];
                if (p.name && !counted.includes(p.name)) {
                    counted.push(p.name);
                    totalAuthorized++;
                }
            }

            return totalAuthorized;
        };
```

**Comment by bmallred** [comment]
The previous count of unique providers was 60. Counting unique products/offerings we now have a total of 79.

We also updated how things are modeled so the new count is

```
        self.totalAuthorized = function () {
            return fedrampData.products().length;
        };
```
